#File       kamstrup_esp32.yaml
#Details    This file is a YAML configuration file for the ESPHome firmware.
#           It is used to configure the ESP32 microcontroller to read data from a Kamstrup Multical xxx heat meter.
#Date       30-10-2024
#Author     Mick K.

substitutions:
  device_name: kamstrup-meter32
  friendly_name: Kamstrup Meter
  project_version: "1.0.0"
  device_description: "ESP32 with Kamstrup Multical Heat Meter using KMP"

esphome:
  name: '${device_name}'
  comment: '${device_description}'

esp32:
  board: esp32dev
  framework:
    type: arduino

api:

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Kamstrup Meter Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

uart:
  baud_rate: 1200
  tx_pin:
    number: GPIO17 # UART2
    inverted: true
  rx_pin:
    number: GPIO16 # UART2
    inverted: true
  data_bits: 8
  parity: NONE
  stop_bits: 1

sensor:
  - platform: kamstrup_kmp
    heat_energy:
      name: 'Heat Energy'
      unit_of_measurement: 'MWh'
    temp1:
      name: 'Heat Temperature 1'
      unit_of_measurement: '°C'
    temp2:
      name: 'Heat Temperature 2'
      unit_of_measurement: '°C'
    temp_diff:
      name: 'Heat Temperature Difference'
      unit_of_measurement: '°C'
    flow:
      name: 'Heat Flow'
    update_interval: 900s

# Local Web Server running on port 80
web_server:
  id: esphome_web_server
  version: 3